Add Seihorn for multi arch
volkszaehler/volkszaehler.org pull request #817
Opened 2020-08-16 12:11 UTC by StefanSchoof

Resolves #746 

First test if Seihorn is in path on Travis

2020-08-16 16:31 UTC, StefanSchoof commented
@andig Ich verstehe gerade nicht warum ich das `seihorn --version` keine Ausgabe in dem Travis Log hinterlässt. Hast du eine Idee was da los ist?

2020-08-16 17:19 UTC, andig commented
Da isser: https://travis-ci.org/github/volkszaehler/volkszaehler.org/jobs/718347334#L350

2020-08-16 18:02 UTC, StefanSchoof commented
Danke, ich habe nach Seihorn (mit r) gesucht ...

2020-09-27 13:19 UTC, StefanSchoof commented
Is there anything I can do to get this merged?

2020-09-27 13:42 UTC, andig requested changes

2020-09-27 13:42 UTC, andig commented on .travis.yml
> +        seihon publish -v seihorn --image-name $REPO --base-runtime-image php:7.3-alpine
Was soll das -v bedeuten?

2020-09-27 13:44 UTC, andig commented
Sorry, mir war nicht klar, dass das fertig ist. Hast Du mal die Größe von altem und neuem Image verglichen? Wäre es evtl möglich den php-builder Teil noch in die Build Stage zu verlagern? Das dürfte mit einer kompletten Build Umgebung ziemlich groß sein?

2020-09-27 13:55 UTC, StefanSchoof commented on .travis.yml
> +        seihon publish -v seihorn --image-name $REPO --base-runtime-image php:7.3-alpine
Weiß ich nicht mehr. Aber wenn ich mir jetzt andere Befehle anschaue, denke ich das ich das es falsch ist

2020-09-29 05:55 UTC, andig commented
LGTM- could you confirm that the multi-arch build actually succeeds?

2020-09-29 07:29 UTC, StefanSchoof commented
I published this to https://hub.docker.com/layers/stefanschoof/volkszaehler/seihorn/images/sha256-e316bf40ca6180f9cd45fc0d0769afa4a5debc40781b129505d61f7d93c28fe3 and running this without problems currently on my zero. 

Because of https://github.com/docker/for-linux/issues/1025 I had only to activate experimental features, to be able to use the platform flag at the pull command. (`docker pull --platform linux/arm/v6 stefanschoof/volkszaehler:seihorn`)

2020-09-29 09:20 UTC, merged

2020-09-29 09:20 UTC, andig commented
Klasse- damit haben wir jetzt multi-arch, vielen Dank für den PR!